// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatGPT(arg1) {
  return window['go']['main']['App']['ChatGPT'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadToken() {
  return window['go']['main']['App']['LoadToken']();
}

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}
